### PR TITLE
UX new Design

### PR DESCRIPTION
**Pull request by BenHurCreations**

### CODE REVIEW

**Comment by BenHurCreations** [comment]
WhatsApp Image 2020-11-07 at 17 55 22

**Review by simzacks — CHANGES_REQUESTED** [review]
There is a legal and ethical issue using images that you don't have the rights to. It is also problematic linking to images on someone else's website because you use up their bandwidth every time your page is loaded.
You should search for images with a creative common license. If you aren't planning on using this site for production, you can look for "not for commercial use" which gives you a wider range of possibilities.
A site that I use for free images is pixabay.com.

**Comment by BenHurCreations** [comment]
which images do you recognize as problematic? 
I can either replace them, or download them and add to the project directory and by that not use their bandwidth

**Comment by simzacks** [comment]
In style.css there are 3 images linked. Do all 3 of those images have licenses that allow you to use them?
That being said, for all the images in the project, are they freely available for use?

**Comment by BenHurCreations** [comment]
I gave it a deep check and as long as the system is not for commercial use- the licences of the photos allow using them. 
However, for better performance and in order to be independent from their servers- I downloaded the photos and uploaded them to the project. Ready to be merged :)

**Pull request merged**
