### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by aryehlev**
this is a real client test with registering a user(not sure what the first files are)

### CODE REVIEW

**Review by simzacks — CHANGES_REQUESTED** [review]
Please remove all the .pyc files from the PR and the .log.
These should all be in the .gitignore

**Comment by aryehlev** [comment]
not sure if it was solved or not- added *.pyc.* and *.log to .gitignore

**Comment by simzacks** [comment]
Look at the Files Changed section:
https://github.com/beyond-io/superx/pull/55/files

You probably have to first remove all the files from your commit, before the .gitignore will have any affect.

**Comment by aryehlev** [comment]
ok, i erased all except for log- not sure why cant erase

**Comment by aryehlev** [comment]
ok i erased and added a few more tests and changes for the tests

**Review by simzacks — CHANGES_REQUESTED** [review]
ubuntu-bionic-18.04-cloudimg-console.log  has to be removed
and most of the test files in the PR don't end with a blank line.

If you look here: https://github.com/beyond-io/superx/pull/55/files
at the files you'll see a red sign at the bottom of the file.
The blank line has to be without spaces or tabs.

**Comment by aryehlev** [comment]
Fixed. if you look there ubuntu-bionic-18.04-cloudimg-console.log has been deleted, and fixed all new lines

**Review by simzacks — APPROVED** [review]

**Pull request merged**
