### PR TITLE
DB structure

### PR DESCRIPTION
**Pull request by BenHurCreations**
EER model for our database including realtionships between tables.
- All relationships are identifying relationshsips

### CODE REVIEW

**Comment by BenHurCreations** [comment]
I managed to sync the EER model with the DB so this comment is nor relevant anymore :)

**Comment by simzacks** [comment]
Is there any way you can upload this file either as an image or a text file?

**Comment by BenHurCreations** [comment]
image

**Comment by simzacks** [comment]
A few assumptions/questions.
* ChainID is assumedly the chainID from the file and is the primary key of the table.
** It may make more sense to include the subchainid in the chain table, and make the primary key a combination of chainid+subchainid. 
* In the Branch Table, what is the primary key? I see that a unique combination here would be chainid, subchainid, branchid
* In the product table, you probably want the manufacturer as well. It actualt doesn't hurt to add all the fields they give you. You may find them useful at some point.
* In the price table, I would add the last updated date
* maximum 12 characters for the password? One secure way of saving the password is to md5 it at the client, and only send/store the encrypted value to the server.
* The user data section needs to be fleshed out a bit more. But I would wait until you're ready to start designing the functionality.

**Pull request merged**
